name: Build ubuntu

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gvmkit-build
        run: |
          wget https://github.com/golemfactory/gvmkit-build-rs/releases/download/v0.3.19/gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          mv gvmkit-build /usr/local/bin
          rm gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          gvmkit-build --version

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: '12.4.1'
          method: 'network'
          sub-packages: '[]'

      - name: Build project
        run: |
          python build-cross.py

      - name: Free some space by removing CUDA libaries
        run: |
          df
          sudo rm -rf /usr/local/cuda*
          df

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda
          path: profanity_cuda
          retention-days: 1
