name: Build ubuntu

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gvmkit-build
        run: |
          wget https://github.com/golemfactory/gvmkit-build-rs/releases/download/v0.3.19/gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          mv gvmkit-build /usr/local/bin
          rm gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          gvmkit-build -h

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: '12.4.1'

      - name: Build project
        run: |
          python build-cross.py

      - name: Create gvmkit image
        run: |
          cp profanity_cuda runtime/
          cd runtime
          docker build -t cuda .
          gvmkit-build cuda --push-to nvidia/cuda-x-crunch:dev-12.4.1
        env:
          REGISTRY_USER: nvidia
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda
          path: profanity_cuda
          retention-days: 1
