name: Build self hosted

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-windows:
    runs-on: windows-gpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          python build-cross.py

      - name: Run benchmark
        run: |
          python benchmark-cross.py

      - name: Cleanup self hosted runner workspace
        continue-on-error: true
        run: |
          git clean -ffdx
