name: Build ubuntu

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: '12.4.1'

      - name: Build project
        run: |
          cmake .
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda
          path: profanity_cuda