name: Build ubuntu

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.19

      - name: Build project
        run: |
          cmake .
          make

      - nane: List files
        run: |
          ls -la
          tree
          

      - name: Upload cuda_profanity
        uses: actions/upload-artifact@v4
        with:
          name: cuda_profanity
          path: particles.dir