name: Build windows

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-windows:
    runs-on: windows-gpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cmake .
          cmd /c build_release_win.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executable
          path: Release/*