name: Build self hosted

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false

jobs:
  build-windows:
    runs-on: cuda-linux-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker
        run: |
          docker build -t profanity_cuda .

