name: Build ubuntu

on:
  push:
    branches: [ "main", "actions/build" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false


jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_570.86.10_linux.run
          sudo sh cuda_12.8.0_570.86.10_linux.run --silent --toolkit --override

      - name: Build project
        run: |
          cmake .
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda
          path: profanity_cuda