name: Build self hosted

on:
  push:
    branches: [ "main", "actions/build", "pattern-generation" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug or release)'
        required: true
        default: 'release'
      target:
        description: 'Optional compilation target'
        required: false

jobs:
  build-and-test-docker:
    runs-on: linux-cuda-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker
        run: |
          docker build -t profanity_cuda .

      - name: Run checks
        run: |
          python -u test/check_pattern_generation.py

      - name: Build vast docker
        run: |
          docker build -t vast_profanity_cuda -f vast/Dockerfile .