name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: '12.4.1'

      - name: Run build script
        run: |
          python build-cross.py
          mv profanity_cuda profanity_cuda-12.4.1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda-12.4.1
          path: profanity_cuda-12.4.1
          retention-days: 1

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-release

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: profanity_cuda-12.4.1

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: profanity_cuda-12.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}