name: Release

on:
  workflow_run:
    workflows: ["Release-build-12.4.1"]
    types:
      - completed

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: profanity_cuda-12.4.1

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: profanity_cuda-12.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}