name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-release-12-4-1:
    name: Build Ubuntu 12.4.1
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.21
        with:
          cuda: '12.4.1'
          use-github-cache: 'false'
          use-local-cache: 'false'
          log-file-suffix: '12.4.1.txt'
          linux-local-args: '["--toolkit"]'

      - name: Run build script
        run: |
          python patch_cuda_architectures.py
          python build-cross.py
          mv profanity_cuda profanity_cuda-12.4.1
        env:
          CUDA_ARCHITECTURES: 61 70 75 80 86 89

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda-12.4.1
          path: profanity_cuda-12.4.1
          retention-days: 1

  build-release-12-8-0:
    name: Build Ubuntu 12.8.0
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cuda toolkit
        uses: Jimver/cuda-toolkit@v0.2.21
        with:
          cuda: '12.8.0'
          use-github-cache: 'false'
          use-local-cache: 'false'
          log-file-suffix: '12.8.0.txt'
          linux-local-args: '["--toolkit"]'

      - name: Run build script
        run: |
          python patch_cuda_architectures.py
          python build-cross.py
          mv profanity_cuda profanity_cuda-12.8.0
        env:
          CUDA_ARCHITECTURES: 61 70 75 80 86 89 90

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profanity_cuda-12.8.0
          path: profanity_cuda-12.8.0
          retention-days: 1

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-release-12-4-1, build-release-12-8-0]

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: profanity_cuda-12.4.1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: profanity_cuda-12.8.0

      - name: Install gvmkit-build
        run: |
          wget https://github.com/golemfactory/gvmkit-build-rs/releases/download/v0.3.19/gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          mv gvmkit-build /usr/local/bin
          rm gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
          gvmkit-build -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create gvmkit image 12.4.1
        run: |
          cp profanity_cuda-12.4.1 runtime/profanity_cuda
          cd runtime
          docker build -f ubuntu2204.dockerfile -t cuda2 .
          gvmkit-build cuda2 --push-to nvidia/cuda-x-crunch:prod-12.4.1
        env:
          REGISTRY_USER: nvidia
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Create gvmkit image slim 12.4.1
        run: |
          cp profanity_cuda-12.4.1 runtime/profanity_cuda
          cd runtime
          docker build -f slim2204.dockerfile -t cuda-slim2204 .
          gvmkit-build cuda-slim2204 --push-to nvidia/cuda-x-crunch:prod-slim-12.4.1
        env:
          REGISTRY_USER: nvidia
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Create gvmkit image 12.8.0
        run: |
          cp profanity_cuda-12.8.0 runtime/profanity_cuda
          cd runtime
          docker build -f ubuntu2404.dockerfile -t cuda3 .
          gvmkit-build cuda3 --push-to nvidia/cuda-x-crunch:prod-12.8.0
        env:
          REGISTRY_USER: nvidia
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            profanity_cuda-12.4.1
            profanity_cuda-12.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}